### ISSUE TITLE
Implicit conversion of types with mat with `=` operator

### ISSUE THREAD

**Issue by JJscott** [JJscott/single_header_math#1]
I would like to be able to implicitly convert matrix types with the `=` operator. The following is currelt invalid:
```C++
basic_mat<float, 4, 4> m = basic_mat<double, 4, 4>{};
```

However the following *is* valid (desired behaviour):
```C++
basic_vec<float, 4> v = basic_vec<double, 4>{};
basic_quat<float> q = basic_quat<double>{};
```

**Comment by benos-9k** [comment]
This is an easier fix than I thought. The `basic_mat` 1-arg magic ctor is currently declared `explicit`; it shouldn't be (see `basic_vec`). @JJscott, feel free to fix instead of me.
